ch08-00-common-collections - Initial translation
IttayWeiss/rustbook-heb pull request #9
Opened 2023-04-25 09:51 UTC by ronyhe

Initial translation for the collections chapter intro.
This is just the intro, rather than the entire chapter, since I'd like to get some feedback and make sure I'm on the right track before continuing.

2023-04-25 09:54 UTC, ronyhe commented on src/ch08-00-common-collections.md
> +הספרייה הסטנדרטית של ראסט כוללת מספר מבני נתונים שימושיים שנקראים *אוספים*. רוב מבני הנתונים מייצגים ערך אחד בעוד אוספים יכולים להכיל ערכים רבים. בניגוד למערך והרצף המובנים, הדאטא שהאוספים הללו מצביע
- האם לתרגם לעברית דאטא ו-היפ?

2023-04-26 06:49 UTC, IttayWeiss commented on src/ch08-00-common-collections.md
> +הספרייה הסטנדרטית של ראסט כוללת מספר מבני נתונים שימושיים שנקראים *אוספים*. רוב מבני הנתונים מייצגים ערך אחד בעוד אוספים יכולים להכיל ערכים רבים. בניגוד למערך והרצף המובנים, הדאטא שהאוספים הללו מצביע
ברוך הבא לפרוייקט התרגום. 

הקובץ HebEngTerms.md מכיל את המושגים הנפוצים בראסט, ואת התרגום שלהם לצורכי הספר. בפרט, Data מתורגם לדאטה (זכר). Hash Map מתורגם למפת גיבוב.

2023-04-26 06:51 UTC, IttayWeiss requested changes
התרגום נראה בסדר גמור, חוץ מהשימוש במונחים הלועזיים, והתייחסות לדאטה בלשון נקבה.

2023-04-26 10:40 UTC, IdanLib commented
הי רוני, מה המצב?
מסכים עם איתי, בגדול זה אחלה לגמרי (ובכל מקרה, תמיד אחרי תרגום ראשוני ישנו סבב עריכה). וכן, את המונח "היפ" יש לתרגם ל-"ערימה." הקובץ HebEngTerms מכיל את הטרמינולוגיה המעודכנת.

2023-04-27 21:42 UTC, ronyhe commented
ברור לי שיהיו סבבי עריכה, בוודאי בהתחלה, הכל טוב :)
לגבי ההערות: און איט

2023-04-27 21:55 UTC, ronyhe commented on src/ch08-00-common-collections.md
> +הספרייה הסטנדרטית של ראסט כוללת מספר מבני נתונים שימושיים שנקראים *אוספים*. רוב מבני הנתונים מייצגים ערך אחד בעוד אוספים יכולים להכיל ערכים רבים. בניגוד למערך והרצף המובנים, הדאטא שהאוספים הללו מצביע
תוקן. תודה על ההכוונה!
ניסחתי מחדש על מנת להימנע מהצורך לתרגם Data  והשתמשתי ב״מפת גיבוב״ במקום ב-Hash Map.

2023-04-27 21:59 UTC, ronyhe commented
תוך כדי שמימשתי את ההערות שמתי לב ש:
- אלא אם אני מפספס משהו, ההתייחסות לדאטא כזכר לא נמצאת במילון המונחים
- ישנו הבדל בין ״מפת גיבוב״ ב-HebEngTerms.ms לבין   ״מיפוי גיבוב״ ב-HebEngTerms.txt
אני מפספס משהו? האם זה במכוון? האם ליצור פול ריקווסטס גם לגבי הנושאים האלה?

2023-04-28 11:58 UTC, IdanLib commented
הי רוני
אתה צודק לגבי HebEngTerms - לא ציינו לאיזה מהם להתייחס. בגדול, קובץ txt הוא הישן יותר, וקובץ ה-md הוא זה המעודכן (אחרי דיונים בנושא הטרמינולוגיה), כך שמה שמופיע בקובץ ה-md הוא הטרמינולוגיה העדכנית. נסיר את הקובץ txt. 

לגבי דאטה - נכון, זה לא מצוין במפורש. אולי באמת כדאי להוסיף. זה פשוט כלל אצבע לפיו התיישרו התרגומים והעריכות הנוכחיות. כנ"ל "ראסט" (במובן של השפה כולה) אליה מתייחסים בלשון נקבה.

2023-04-28 14:55 UTC, IttayWeiss approved these changes
אחלה :) תרגיש חופשי לעשות מרג'.

2023-04-30 14:25 UTC, ronyhe commented
> אחלה :) תרגיש חופשי לעשות מרג'.

אני? אני לא חושב שיש לי את האפשרות

2023-04-30 14:38 UTC, merged

2023-04-30 14:41 UTC, IttayWeiss commented
צודק לגמרי. עשיתי מרג'. שם לב, אגב, שיש issues מוכנים כבר לתרגום המשך הפרק. אם בא לך, אתה יכול לנכס לעצמך את ה-issue הבא.